var pastanames = ['navyseal', 'daddy', 'showdownmod', 'gw', 'vietnam', '400ping', 'ja', 'republican', 'boneless', 'anime', 'never', 'assaulthelicopter', 'saveglitch', 'fattyboomboom', 'wheelchair', 'animejp', 'animeen', 'riot', 'goodshit', 'sun', 'shia', 'americantest', 'dankvirus', 'memedog', 'system32', 'davinci', 'papyseal', 'fail', 'calculus', 'emojimovie', 'dlc']
var copypastas = ['What the fuck did you just fucking say about me, you little bitch? I’ll have you know I graduated top of my class in the Navy Seals, and I’ve been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I’m the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You’re fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that’s just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little “clever” comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You’re fucking dead, kiddo.',
  ":angel: daddy's :heart::sweat_drops::eggplant: little fidget spinner:dizzy: when daddy :revolving_hearts: feels horny he lifts :truck: me up:point_up:️ and puts me on:on: his huge :weary::sweat_drops:dick:eggplant: and I spin :cyclone: and spin :cyclone: whirrrrrr :flushed::flushed:I get:ideograph_advantage: so:sos: dizzy:dizzy: but daddy:revolving_hearts: keeps spinning :dizzy: me untill I squirt:fountain::fountain: leaving me all wet:sweat_drops: and his cummies :baby_bottle::baby_bottle: are all inside:diamond_shape_with_a_dot_inside: me:flushed: god I'm such a:flushed: spinny :dizzy_face:dizzy:dizzy_face::dizzy_face: little slut for daddy!",
  "I sexually Identify as a Showdown Mod. Ever since I was a girl I dreamed of soaring over the chatrooms dropping hot sticky locks on disgusting chat trolls. People say to me that being a Showdown Mod is Impossible and I’m fucking retarded but I don’t care, I’m beautiful. I’m having a plastic surgeon install a Hitler moustache, 30mm banhammers and Z4-R3L Hellfire Lockers on my body. From now on I want you guys to call me \"Aurora\" and respect my right to mute from above and ban needlessly. If you can't accept me you’re a modophobe and need to check your usergroup privilege. Thank you for being so understanding.",
  ":flag_us::flag_us::flag_us: Shoutout :speaking_head: to :arrow_right:️ George Washington :grin: and :heavy_plus_sign: the boys :man:‍:boy:‍:boy: for inventing :thinking: freedom :ok_hand: :flag_us::flag_us::flag_us:",
  "Six hasn't been the same since he left Vietnam. He can seldom close his eyes without opening them again at fear of Charlies lurking in the jungle trees. Not that you could ever see the bastards, mind you. They were swift, and they knew their way around the jungle like nothing else. He remembers the looks on the boys' faces as he walked into that village and... oh, Jesus. The memories seldom left him, either. Sometimes he'd reminisce - even hear - Tex's southern drawl. He remembers the smell of Brooklyn's cigarettes like nothing else. He always kept a pack of Lucky's with him. The boys are gone, now. He knows that; it's just that he forgets, sometimes. And, every now and then, the way that seven looks at him with avid concern in his eyes... it makes him think. Sets him on edge. Makes him feel like he's back there... in the jungle.",
  "Hello am 48 year man from somalia. Sorry for my bed england. I selled my wife for internet connection for play \"conter strik\" and i want to become the goodest player like you I play with 400 ping on brazil and i am global elite 2. pls no copy pasterio my story",
  "Hi, sorry for englise......is 2nd language jajaja :D.... My friend tell me dat this Sampsons actor is name Ms Kebab Apple?? ..... Is dis confirm? Jajajajaja xD ...... I think kebab is a food xD my friend also say \"Bart Sampson\" say to her \"eat my pants\" WTF jajajajaja xD",
  "Did you ever hear the tragedy of Donald Trump The Wise? I thought not. It’s not a story the Democrats would tell you. It’s a Republican legend. Donald Trump was a Dark President of the Republican Party, so tremendous and so wise he could use the executive branch to influence the taxpayers to create walls… He had such a knowledge of the conservative side that he could even keep the ones who supported him from fact-checking his statements. The right side of the political spectrum is a pathway to many abilities some consider to be unnatural. He became so powerful… the only thing he was afraid of was losing his power, which eventually, of course, he did. Unfortunately, he taught his apprentice everything he knew, then his apprentice shocked him for being gay. Ironic. He could save others from theocracy, but not himself.",
  "ya pizza what u want?\nlemme get uhhhhhhhhhh\nboneless pizza wit a 2 liter of coke\nfuk kind of pizza??\nand 2 liter machine broke\nwe got 1 liter tho\nfuk u mean B\naight look lemme get that pizza boneless\nuh? pizza dont got bone on it\ntf did i just say then\nyou said, lemme get it boneless\nlike pizza got a dam bone in it\nyall got bones in ya sht then\nnah\nso whats the problem\nD1CK HEAD\nname one pizza that got bone on it\njust dont put them shts in my pizza bruh\nhow many times i gotta say it\nbruh just explain to me\nhow the fuk pizza can be boneless?\nif it dont got bone in it iss boneless\nson what school u go to\ndawg i don't understand the problem\njust make my sht boneless",
  "Yes anime are for kids. Kids at the age of 5 and above have a perfectly fit brain to be nurtured by the values passed through anime. Any kid that has only watched retarded cartoons throughout his childhood will probably never even touch them as a teenager. Simply because the idea of anime being “stupid Chinese stuff for nerds“ will already have sinked in. As a result they will have no real values in their lives. I believe this to be the reason of at least 80% teenage population nowadays turning into SWAGfags and YOLOtards. They only watch shit like that spongebob squaretard, the most disgusting, moronic cartoon ever made. Remade batman series, remade pokemon series, remade YU-Gi-Oh series that have lost any good messages the original script wanted to pass on... Our generation grew up by watching Dragon Ball probably under the age of 10. Why shouldnt the generations after us do the same? Show the little ones around you the culture of anime. Let them grow a properly functioning brain. Anime is the only way.",
  "Oh my god. It finally happened. We're finally at the end. Let's do it. Oh boy. Here we go oh my god. Oh my god. We've done it. We've reached the legendary three digit level. click never ever ever ever do this. This is the dumbest thing you could possibly do. Reach level one hundred on steam. Listen, ok? Never do this. Never.",
  "I sexually Identify as an Attack Helicopter. Ever since I was a boy I dreamed of soaring over the oilfields dropping hot sticky loads on disgusting foreigners. People say to me that a person being a helicopter is Impossible and I’m fucking retarded but I don’t care, I’m beautiful. I’m having a plastic surgeon install rotary blades, 30 mm cannons and AMG-114 Hellfire missiles on my body. From now on I want you guys to call me “Apache” and respect my right to kill from above and kill needlessly. If you can’t accept me you’re a heliphobe and need to check your vehicle privilege. Thank you for being so understanding.",
  "NOW HOLD THE FUCK UP:triumph::rage:did i just see you :eyes::fearful:do the save glitch :scream::confounded:in this speedrun? :dizzy_face::imp:if only you were a real:ok_hand::clap: speed-runner:runner::dash: like i am, :sunglasses::innocent:you would know:thinking::rolling_eyes: that the save glitch glitch:joy::joy::joy: is completely out of bounds. :wave::x::no_pedestrians:so unless you mistyped :keyboard::computer:the title saying:speaking_head::speaking_head: INBOUNDS :speaking_head::speaking_head:when you mean the out of bounds, :scream::rolling_eyes:then i can forgive that :innocent::confused:But what is UNFORGIVABLE:imp::imp::imp: is performing the save glitch:no_good::x::x: in the inboundaries category :astonished::thermometer_face::mask:i cannot believe:cold_sweat::cold_sweat: people like this:smiling_imp::japanese_ogre: exist, disgusting:cry::sob::frowning2:️",
  "Welcome to Africa, lady. If it's your first time in the concrete jungle, just sit back and relax. Everything is going to be okay, heh heh heh heh. Now we are stopping a robot. People from overseas, they like that one. Because they say \"What do you mean, ROBOT?!\" Because in South Africa we call a traffic light a robot. They love that one. Over there we have some very naughty hyenas eating the rubbish. Ah! These hyenas, they make such a big mess! Over there is a shop owner chilling with his black panther. Nobody is going to steal nothing when he's chilling with that black beauty. Nobody. Ah, ah, ah! Let me tell you it is your lucky day! Over there is the king of the concrete jungle- the Lion King! [Something in another language] And here we have some local musicians about to kick some funky tunes. (Oh my God, look at their freaky fashion! I should get 'em to open for me.) Oh fuck. (The fuck? DROP YOUR FUCKING WEAPON! DROP YOUR FUCKING WEAPON! SHUT THE FUCK UP! DROP YOUR FUCKING WEAPON! SHUT THE FUCK UP!) [gunfire]",
  "My dad had a bad habit of bursting into his teenaged son's bedroom without knocking. Normally it was fine cos I could hear him walking down the hallway, but he had his leg amputated and lived his last few years in a wheelchair. Rolling is much quite than walking... So, one time I was jerking to porn on my computer, and he burst in right when I was at the point of no return. I just dropped out of my chair and hit the floor, spurting cum everywhere. The was a silence for a few seconds then I just heard him roll backwards and quietly close the door. Neither of us ever mentioned it.",
  "アニメは人生の不可欠な部分です。ジェンダーやレースのも関わらず、すべてアニメはかわいいです。しかし、すべてのアニメが日本語であるとは限ねー、ほとんどの人が考えるように。アニメは日本、韓国、中国、アメリカ、またはスウェーデンから来ることができる。アニメ女子は大きくて丸い目をある、と彼らの髪の上に広がる目と彼らの顔から離れて。彼らはにおいをすることさえしない非常に小さな鼻をおそらく持っている。彼らの口はほとんどいつも開いている、そうでない場合彼らは隠されたオルガスムを持っている。だから彼らは微笑っている、またはちょうど悲しい。彼らの髪はめっちゃに長く、足首又はその下まで伸びている。彼ら髪の色は、通常、赤、青、青、緑、ピンク、またはほかのような人工の色です。茶色、金髪、黒髪のアニメを持つことは可能ですが、ほとんどのアニメは髪の色を染めたあった。彼らのバストサイズは常にかなり大きいです。これの良い例は、初音ミクです。彼女はシアン色の髪をしている。彼女の髪は彼女のブーツに行く、約六十九メートル。彼女は短いスカートを持っており、全体的にかなりみだらなです。彼女は歌っているので、口が開いている。しかし神は彼女がオルガスムの真ん中にいるかどうか知っている。彼女がアニメであることを知って、チャンスは彼女です。なぜか分かないが、企業はアニメ女子と動物を混ぜている。そしてそれはかなりくそ暑いです。彼らは猫の女子とキツネの女の子のような融合物を作った。それらのすべてはまだかなりかわいいですが、彼らは何らかの理由でパンティーを唯一着る。僕は誰も見ていないときに彼ら自身と遊ぶと聞いた。そのため、すべてのアニメゲームは「十八」以上です。彼ら作るは僕たちの望みを猫用疑う、またなぜ僕たちは彼らのための勃起を得る。しかし正直なところ、誰もそれを気にしない。僕たちはすべて、淫のアニメを見るのが大好きです、ね？ 僕たちはまたそれらを性交したい。めっちゃ硬い。それから、僕たちはできないと分かり、悲しくなる。だから僕たちは代わりに自慰する。アニメの男の子はあまり面白くないですが、彼らはまだかなりかわいいですね。僕がバイセクシャルではないので、これを解読するのは難しいことです。さようなら。",
  "Anime is an essential part of life. Every single anime is cute no matter gender or race. However, not all anime are Japanese, as most people think. Anime can come from Japan, Korea, China, or even America and Sweden. Anime girls have big round eyes that extend over their hair and off their face. They have a very small nose that they probably don’t even use to smell with. Their mouth is almost always open, and if it isn’t open they’re just having a hidden orgasm, so they are either smiling or just plain sad. Their hair is very long, and extends either down to their ankles or below. Their hair color is usually an artificial color like red, blue, teal, green, pink, or otherwise. It is possible to have brown, blonde, or black haired anime, but most anime have dyed hair colors. Their bust size is always quite large. A good example of this is Hatsune Miku. She has teal colored hair and it goes down about 69 meters down to her boots. She has a short skirt and is overall pretty lewd. She is singing so her mouth is open, but god knows if she’s in the middle of an orgasm. Knowing she’s an anime, chances are she is. I don’t know why, but companies have put anime girls with animals. And it’s pretty damn hot. They created fusions like catgirls, fox girls, and many others. All of them are still pretty cute, but they only wear panties for some reason. I heard they play with themselves when nobody is watching. That’s why all anime games are 18+. They make us question our sexuality and why we get a boner for felines. But let’s be honest, nobody cares about that. We all love seeing lewd anime. Right? We also want to fuck them. Real hard. And we get sad when we realize we cannot. That is what masturbation is for. Anime boys aren’t very interesting but they’re still pretty cute I guess. It’s kind of hard for me to decipher this because I’m not bisexual. Bye.",
  "O-oooooooooo AAAAE-A-A-I-A-U- JO-oooooooooooo AAE-O-A-A-U-U-A- E-eee-ee-eee AAAAE-A-E-I-E-A-JO-ooo-oo-oo-oo EEEEO-A-AAA-AAAA",
  " 👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌th 👌 ere👌👌👌 right✔there ✔✔if i do ƽaү so my selｆ 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit",
  "I sexually Identify as an the sun. Ever since I was a boy I dreamed of slamming hydrogen isotopes into each other to make helium & light and send it throught the galaxy. People say to me that a person being a star is Impossible and I’m fucking retarded but I don’t care, I’m beautiful. I’m having a plastic surgeon inflate me with hydrogen and raise my temperature to over 6000 °C. From now on I want you guys to call me “Sol” and respect my right to give you vitamin D and probably sunburns. If you can’t accept me you’re a fusionphobe and need to check your astral privilege. Thank you for being so understanding.",
  "DO IT JUST DO IT. Don't let your dreams be dreams, Yesterday you said tomorrow, SO JUST DO IT MAKE YOUR DREAMS COME TRUE, JUST DOOOOO IT. Some people dream of success while you're gonna wake up and work HARD AT IT NOTHING IS IMPOSSIBLE. You should get to the point where anyone else would quit and you're not gonna stop there! NO WHAT ARE YOU WAITING FOR? DO IT! JUST DO IT! YES YOU CAN, JUST DO IT! If you're tired of starting over, STOP GIVING UP.",
  "✓ Obesity ✓ 💥🔫 ✓ Laziness ✓ Stupidity ✓ 🌵 ✓ McDonald's ✓ Donald Trump ✓ $70k College ✓ Bad healthcare ✓ Bad food ✓ Bad music ✓ Fahrenheit ✓ Pounds ✓ Inches ✓ AMERICAN TEST PASSED",
  "bᎽ ᏒᎬᎪᎠᎥᏁᎶ ᏆhᎥs mᎬssᎪᎶᎬ ᎽᎾu ᎪᏒᎬ ᏁᎾᎳ ᎥᏁfᎬᏟᏆᎬᎠ ᎳᎥᏆh ᏆhᎬ ᎠᎪᏁᏦ ᏢᎪsᏆᎪ ᏉᎥᏒus. ᏆᎾ ᎶᎬᏆ ᏒᎥᎠ Ꮎf ᏆhᎬ ᎠᎪᏁᏦ ᏢᎪsᏆᎪ ᏉᎥᏒus, ᎽᎾu musᏆ ᏢᎪss ᎥᏆ ᎾᏁ ᏆᎾ ᏆhᎬ ᏟhᎪT ヽ༼ຈل͜ຈ༽ﾉ I'm cured!!",
  "╭━━━━╮ This is memedog. Help\n╰┃ ┣▇━▇ memedog take over\n ┃ ┃  ╰━▅╮ Discord by pasting\n ╰┳╯ ╰━━┳╯ him in 10 other\n  ╰╮ ┳━━╯ discord servers or he\n ▕▔▋ ╰╮╭━╮ will never be a meme dog.\n╱▔╲▋╰━┻┻╮╲╱▔▔▔╲\n▏  ▔▔▔▔▔▔▔  O O┃\n╲╱▔╲▂▂▂▂╱▔╲▂▂▂╱\n ▏╳▕▇▇▕ ▏╳▕▇▇▕\n ╲▂╱╲▂╱ ╲▂╱╲▂╱",
  "Hello, I have been informed that you have the system32 virus. The system32 virus does a UDP attack on your router on any open port so your internet throttles and lags and it has a very bad frame drop from 30 fps!, Not only that, It stops you from adding some people on steam and downloading some of the most recent games!, It uses up more of your HardDrive per launch on your computer etc, To delete this do: open cmd type in \"cd system\" without the quote marks then type in del system32 Press enter And there you go! Your system32 virus is deleted! (Its a fake copy of the system file that does all virus and downloads secret trojans, AV can't detect them since its in the computer's windows file and if its in there it could potentially damage your computer because it leaves logs there. Thank you! -Twitch Support",
  "“wtf his ult did like 3k damage how is that legit” – leonardo da vinci 1496, founder of the Illuminati",
  "WHAT THE SPAGHETTI DID YOU JUST SAY ABOUT ME, YOU HUMAN? I’LL HAVE YOU KNOW I GRADUATED TOP OF MY CLASS IN THE ROYAL KNIGHTS, AND I’VE BEEN INVOLVED IN NUMEROUS SECRET RAIDS ON SNOWDIN, AND I HAVE OVER 300 CONFIRMED PUZZLES. I AM TRAINED IN BLUE ATTACKS AND I’M THE TOP MONSTER IN THE ENTIRE UNDERGROUND. YOU ARE NOTHING TO ME BUT JUST ANOTHER TARGET. I WILL WIPE YOU OUT WITH COOL DUDE BONES THE LIKES OF WHICH HAS NEVER BEEN SEEN BEFORE ON THIS EARTH, MARK MY SUPERIOR WORDS. YOU THINK YOU CAN GET AWAY WITH SAYING THAT NONSENSE TO ME OVER THE UNDERNET? NYEH HEH HEH! THINK AGAIN, HUMAN. AS WE SPEAK I AM CONTACTING MY SECRET NETWORK OF DOGS ACROSS THE UNDERGROUND AND YOUR CELL PHONE IS BEING TRACKED RIGHT NOW SO YOU BETTER PREPARE FOR YOUR CAPTURE, HUMAN. THE CAPTURE THAT WILL ALLOW ME TO PROVE TO UNDYNE ONCE AND FOR ALL HOW GREAT I AM! YOU’RE FINISHED, HUMAN. I CAN BE ANYWHERE, ANYTIME, AND I CAN DATE YOU IN OVER SEVEN HUNDRED WAYS, AND THAT’S JUST WITH MY RATTLING BONES. NOT ONLY AM I EXTENSIVELY TRAINED IN BLUE ATTACKS, BUT I AM AN EXCELLENT COOK AND I WILL USE MY COOKING SKILLS TO SHOW MY SUPERIOR LOVE FOR PASTA!!! IF ONLY YOU COULD HAVE KNOWN WHAT GRAND RETRIBUTION YOUR LITTLE “CLEVER” FLIRTING WAS ABOUT TO BRING DOWN UPON YOU, MAYBE YOU WOULD HAVE HELD YOUR TONGUE. BUT YOU COULDN’T, YOU DIDN’T, AND NOW YOU’RE PAYING THE PRICE, SILLY HUMAN. BEING THE GREAT PAPYRUS, I HAVE NEVER BEEN BEATEN IN DATING, AND I NEVER WILL! NYEH HEH HEH!",
  "▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄\n████▌▄▌▄▐▐▌█████\n████▌▄▌▄▐▐▌▀████\n▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
  "Listen kid. I swear to you, I have the top grades in my advanced placement calculus class. You little punk, you will never bring me down in my level of solving for x. Plebs like you have no clue what I needed to do to get a 99.9% in my final. And that's uncurved. Everyone else got 54% or lower. I say to you, screw you kid. I hate every little drop of your blood, which is exactly 4,384,382,172,495,382,384 little blood cells in you that I despise, and I did that by making my own formula dealing with looking at someone's eye color. You kid. You'll never surpass me in the 6 computer programming languages that I created, and the additional 58 that I know. I started learning advanced statistics even before I began to study English. I became a master at integral calculus with multiple variables at age 5. Little puny plebeians such as you can never imagine to become as good as me.",
  "The Emoji Movie unlocks the never-before-seen secret world inside your smartphone. Hidden within the messaging app is Textopolis, a bustling city where all your favorite emojis live, hoping to be selected by the phone's user. In this world, each emoji has only one facial expression - except for Gene, an exuberant emoji who was born without a filter and is bursting with multiple expressions. Determined to become \"normal\" like the other emojis, Gene enlists the help of his handy best friend Hi-5 and the notorious code breaker emoji Jailbreak. Together, they embark on an epic \"app-venture\" through the apps on the phone, each its own wild and fun world, to find the Code that will fix Gene. But when a greater danger threatens the phone, the fate of all emojis depends on these three unlikely friends who must save their world before it's deleted forever.",
  "I have spent about $16,000 worth of DLC and In-Game video game items, and you know what? I don't give a fuck. My parent's credit card is always loaded with that yummy cash, so why the fuck would I not waste it? I need those CS:GO knives, those FIFA card packs, I need all the virtual hats I can get. If I see someone with something better than me, I will buy something that is better than their thing, because I fucking hate it when people have better stuff than me. I haven't been caught yet, because my parents don't know the difference between the electricity bill and the online store bill. Which is why I will continue to buy more shit, until I die. I fucking love DLCs."
  ]
exports.run = (client, message, args) => {
    for(var i = 0; i < pastanames.length; i++) {
    if(args[1] === undefined) return;
    var checkpasta = args[1].toString();
    if(args.length === 1 || args.length > 2){return;}
    if(checkpasta === pastanames[i]){
      message.channel.send(copypastas[i])
      return;
    } else if(checkpasta === 'list'){
      message.channel.send({embed: {
        color: 15784782,
        title: ":newspaper: Copypasta name list: (can i get a Kreygasm :wink:)",
        description: pastanames.join(', ')
      }})
      break;
    }
  }
}
